### ISSUE TITLE
ImageFilters fails to render base64 data uri

### ISSUE THREAD

**Issue by moconnor59** [GregoryNative/react-native-gl-image-filters#13]
I'm attempting to use Expo / ImageFilters with a local image (from the camera) using a uri that looks like '_data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEA..._' however it's failing with error "**EXGL: Invalid pixel data argument for gl.texImage2D()!**". The same code works fine with a regular uri as in the README example.

The comments in _https://github.com/gre/gl-react/issues/140_ imply this may be an Expo issue, however I'm able to use a react-native Image component in place of ImageFilters and it works fine (so I don't think Expo is the problem).

Can ImageFilters be used with a local (in-memory) image?

My setup:
    expo: ^35.0.1,
    expo-camera: ~7.0.0,
    expo-gl: ^8.3.1,
    expo-image-manipulator: ~7.0.0,
    gl-react: ^4.0.1,
    gl-react-expo: ^4.0.1,
    react-native-gl-image-filters: ^0.1.1,

**Comment by GregoryNative** [comment]
@moconnor59 Thanks for issue. I will have a look on the weekend

**Comment by GregoryNative** [comment]
@moconnor59 I've digged this a little bit and probably it's expo issue as Expo does not have loader for base64 image. As you can see in source I am just passing children as it as, same as on gl-react side.
