### ISSUE TITLE
ImageFilters parameter value ranges?

### ISSUE THREAD

**Issue by moconnor59** [GregoryNative/react-native-gl-image-filters#16]
Question: where can I find information / documentation about allowed ImageFilters parameter values / ranges - e.g. what values are allowed for blur, hue, saturation, etc. and what is their effect? (Note: I'm unable to understand the GLSL fragments where these parameters are used in the source code).

**Comment by GregoryNative** [comment]
@moconnor59 Right now, you can only play with it by yourself, but it's good point. I will add it to README.md

**Comment by GregoryNative** [comment]
@moconnor59 Published to [0.2.0](https://www.npmjs.com/package/react-native-gl-image-filters).

**Comment by moconnor59** [comment]
Thanks!
