### ISSUE TITLE
custom filter for black and white

### ISSUE THREAD

**Issue by dipeshkoirala21** [GregoryNative/react-native-gl-image-filters#19]
Hello everyone, i need to apply black and white filter to a image..There is no predefined filter for B & W.. Is there a way to create such filter?

**Comment by GregoryNative** [comment]
@dipeshkoirala21 hello. For black you can use saturation, but for white that is not yet available. Probably you are talking about luminance or exposure. I will add this filter in next release and ping you

**Comment by dipeshkoirala21** [comment]
Sure,Thanks. Is there other way to achieve it for the time being? yk, like combination fliters like hue and sepia and some other?

**Comment by GregoryNative** [comment]
@dipeshkoirala21 That was not possible. But good idea is that it's available now in version 0.2.2. Please, use new **exposure** filter.
