### ISSUE TITLE
configuration with name 'default' not found.

### ISSUE THREAD

**Issue by mopilo** [GregoryNative/react-native-gl-image-filters#2]
that is the errror i got after install and linking every thing

**Comment by GregoryNative** [comment]
Can you put here your **package.json**?

**Comment by mopilo** [comment]
you asked for my package.json. this it.


{
  "name": "lifeStyle",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "gl-react": "^3.15.0",
    "gl-react-native": "^3.15.0",
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-camera": "^1.0.2",
    "react-native-circular-progress": "^0.2.0",
    "react-native-gl-image-filters": "^0.0.4",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-vector-icons": "^4.5.0",
    "react-native-video": "^2.0.0",
    "react-navigation": "^1.5.7",
    "rn-camera-roll": "^0.0.5",
    "sec-to-min": "^1.0.1"
  },
  "devDependencies": {
    "babel-jest": "23.0.0-alpha.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "23.0.0-alpha.0",
    "react-test-renderer": "^16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "asset/fonts"
    ]
  }
}

**Comment by GregoryNative** [comment]
I guess that gl-react and gl-react-native is too high version. This lib has peer depencenies with gl-react and gl-react-native version 2. I will check if it's a problem and let you know.

**Comment by GregoryNative** [comment]
Please check installation again, new version of gl-react and gl-react-native is not work for this lib yet. Use v2 instead of v3 for now. I will figure it out and update it in future.

**Comment by mopilo** [comment]
No example project??

**Comment by GregoryNative** [comment]
I will add it tomorrow 💃

**Comment by mopilo** [comment]
okay then

**Comment by hassaanahmedqureshi** [comment]
Did he posted any example project?

**Comment by mopilo** [comment]
Am not sure, me is waiting

**Comment by GregoryNative** [comment]
Have no idea, maybe you did something wrong.

1. `git clone https://github.com/GregoryNative/react-native-gl-image-filters.git`
2. `cd react-native-gl-image-filters/example`
3. `npm install`
4. `react-native run-is`

Working good for me.

**Comment by mopilo** [comment]
Exactly what i did, but in my case its run-android

**Comment by GregoryNative** [comment]
I found a problem, works for my android device too. @mopilo Can you check it?

**Comment by mopilo** [comment]
yea, buh keep getting this error **more than one library with package name 'com.projectseptember.RNGL'**, when i checked  MainApplication in the android folder this appeared twice **import com.projectseptember.RNGL.RNGLPackage;**

**Comment by mopilo** [comment]
Since its working am gonna close this issue.

**Comment by chandumatrix004** [comment]
Unable to resolve module @unimodules/core from D:\Camera App\Camera-App\node_modules\webgltexture-loader-expo\lib\DeprecatedExpoGLObjectTextureLoader.js: @unimodules/core could not be found within the project or in these directories:
[19:05:22]   node_modules\webgltexture-loader-expo\node_modules
[19:05:22]   node_modules
[19:05:22]
[19:05:22] If you are sure the module exists, try these steps:
[19:05:22]  1. Clear watchman watches: watchman watch-del-all
[19:05:22]  2. Delete node_modules and run yarn install
[19:05:22]  3. Reset Metro's cache: yarn start --reset-cache
[19:05:22]  4. Remove the cache: rm -rf /tmp/metro-*
[19:05:22]    8 | var _webgltextureLoader = require("webgltexture-loader");
[19:05:22]    9 |
[19:05:22] > 10 | var _core = require("@unimodules/core");
[19:05:22]      |                      ^
[19:05:22]   11 |
[19:05:22]   12 | function _defineProperty(obj, key, value) { if (key in obj) { Object.defineProperty(obj, key, { value: value, enumerable: true, configurable: true, writable: true }); } else { obj[key] = value; } return obj; }

I DON'T know how many packages I'll have to install!! I've installed all the packages mentioned in package.json of the snack example link. Still I'm getting millions of errors!! Totally frustrated!
