### ISSUE TITLE
How can i contain the image in ImageFilters? 

### ISSUE THREAD

**Issue by dipeshkoirala21** [GregoryNative/react-native-gl-image-filters#24]
![Screenshot_20201013-104541_ISAC_SIMO 1](https://user-images.githubusercontent.com/25838241/95817708-e1f69100-0d41-11eb-93e3-786427d1443c.jpg)
![Screenshot_20201013-104547_ISAC_SIMO 1](https://user-images.githubusercontent.com/25838241/95817734-f5a1f780-0d41-11eb-9929-431bfe65181f.jpg)

Here the cropped image has the different aspect ratio . After cropping the image, the image gets passed to the ImageFilter component which stretches the image and the same image gets captured with glView.Capture() method which is very annoying.. Can somebody help me on this?

**Comment by dipeshkoirala21** [comment]
Sorry for closing it and reopening it again. I thought i found the solution but it didn't worked as expected.

**Comment by GregoryNative** [comment]
I am not sure how this library related to your problem @dipeshkoirala21

**Comment by dipeshkoirala21** [comment]
sorry, my bad. I should have assigned this issue in gl-react-native library.
