### ISSUE TITLE
Issue while loading remote image

### ISSUE THREAD

**Issue by mbpictures** [GregoryNative/react-native-gl-image-filters#26]
Hi!

I saw the documentations leaks a bit: The type definitions instruct me to have a child component of type "ReactElement", while the docu says an object with key "uri" will also work.

So I added an image component as a child of the image filter component, but it doesn't work (warning: node can not be rendered).

I adjusted the type file so it accepts an object with Uri and a react element and used the object variant and everything works now. So please update the type definitions!

Thanks already for your awesome work! :)

**Comment by GregoryNative** [comment]
Hey @mbpictures. I will appreciate if you add PR with typo fix to develop branch. I am definitely add that to next release.

Thanks!

**Comment by mbpictures** [comment]
Hi!

I created the PR [#28 ](#28 ). Thanks already for merging!

**Comment by GregoryNative** [comment]
Done. Thanks!
