### ISSUE TITLE
gl-shader Eroor: compiling shader

### ISSUE THREAD

**Issue by parice02** [GregoryNative/react-native-gl-image-filters#36]
Hi.
When I run the  [expo example](https://snack.expo.io/@gregoryrn/expo-gregorynative-react-native-gl-image-filters) and [react native example](https://github.com/GregoryNative/react-native-gl-image-filters/tree/master/examples/react-native) on my android, I get this error:

gl-shader: Error compiling shader:
Compile failed.
ERROR: 0:1: '' : Invalid directive 2
1 compilation errors. No code generated.

Please, what is this due to?

Android 10
gl-react: 4.1.0,
gl-react-expo: 4.1.0,
expo-gl: 9.2.0,
buffer: 5.7.1
expo sdk 40 ejected

Thank you.

**Comment by GregoryNative** [comment]
@parice02 Hey, I will have a look this weekend and update it.

**Comment by GregoryNative** [comment]
@parice02 I've updated an expo example https://github.com/GregoryNative/react-native-gl-image-filters/tree/master/examples/expo

**Comment by parice02** [comment]
> @parice02 I've updated an expo example https://github.com/GregoryNative/react-native-gl-image-filters/tree/master/examples/expo

Hello. Thank you. I'll take a look.
