### ISSUE TITLE
Black screen showing when passing base64 image

### ISSUE THREAD

**Issue by umerchaudhary34** [GregoryNative/react-native-gl-image-filters#38]
- Black screen is showing when I'm passing base64 in uri like this i.e {{uri: `data:image/png;base64,${image64}`}}.
- anyone have any solution for that?

**Comment by GregoryNative** [comment]
Hello @umerchaudhary34. Uri is just passed as children down and not manipulate with it at all. The library uses gl-react, gl-react-native, etc, that depends on your project. You can open your issue there.
