### ISSUE TITLE
"Compilation failed; see the compiler error output for details", Cannot resolve this issue!

### ISSUE THREAD

**Issue by hassaanahmedqureshi** [GregoryNative/react-native-gl-image-filters#4]
I have properly installed all three packages i.e.

gl-react-native@2.48.0
gl-react@2.2.0
react-native-gl-image-filters

in a native android studio application. Further I have configured for android as mentioned in the tutorial but still I face this issue of which I cannot find a solution.

**Comment by GregoryNative** [comment]
I think it's related to latest version of react-native, cause it's work in example here, https://github.com/GregoryNative/react-native-gl-image-filters/tree/master/example. You can try it.
