### ISSUE TITLE
can not run project after installing 

### ISSUE THREAD

**Issue by Merrick17** [GregoryNative/react-native-gl-image-filters#40]
Hello I've followed the documentaion and an example of the install and i got this error. 
i'm using React Native CLI not Expo  
![image](https://user-images.githubusercontent.com/25400839/116814419-cd98ab00-ab50-11eb-9e92-8952cef819fa.png)

**Comment by GregoryNative** [comment]
Hi @Merrick17 . Thanks for your issue. I will take a look and let you know.

**Comment by GregoryNative** [comment]
Hello again @Merrick17 . I have updated an example, please have a look into [examples/android](https://github.com/GregoryNative/react-native-gl-image-filters/tree/master/examples/react-native) folder.

**Comment by Merrick17** [comment]
![image](https://user-images.githubusercontent.com/25400839/117366743-22258880-aeb9-11eb-96a2-a8f9ee05bf05.png)
@GregoryNative  deffirent issue after installing NDK

**Comment by GregoryNative** [comment]
Hi @Merrick17 , hm looks like your problem is not related to this particular library. From the error logs I can propose you to open issue in expo-gl-cpp library.

Good luck!
