### ISSUE TITLE
Surface size different than image size

### ISSUE THREAD

**Issue by zerobytes** [GregoryNative/react-native-gl-image-filters#5]
It is currently not possible to have with or height of the image higher than the surface area.
- Surface should keep the size without distorting the image inside of it. 
- ImageFilter component, which has its own height and width properties, should behave normally respecting the values of its width and height and not be distorted by surface, but only "cutted" when its size is bigger than the surface containing it

**Comment by GregoryNative** [comment]
Could you also provide screenshots now and how it should look? It would be much easier to do it. @zerobytes
