### ISSUE TITLE
Using asset-library as URI is resulting in a black surface

### ISSUE THREAD

**Issue by lees106** [GregoryNative/react-native-gl-image-filters#51]
Hello! I was wondering why the surface is rendering this black canvas? I cant seem to make this work with expo media library or @react-native-community/cameraroll. I tried using a normal uri from google images and that works fine, just seems like it doesnt like "assets-library://".  Any help will be appreciated, thanks!!!

<img width="652" alt="Screen Shot 2021-07-05 at 11 13 27 AM" src="https://user-images.githubusercontent.com/47095245/124518419-0720a900-dd82-11eb-9147-2db8998ab430.png">

<img width="381" alt="Screen Shot 2021-07-05 at 11 14 03 AM" src="https://user-images.githubusercontent.com/47095245/124518454-1bfd3c80-dd82-11eb-8f63-5b6c80fe2e0e.png">

**Comment by GregoryNative** [comment]
@lees106 Hello. That looks like Expo (gl-react-expo) does not have loader for assets-library images. As you can see in source I am just passing children as it as:
https://github.com/GregoryNative/react-native-gl-image-filters/blob/master/src/ImageFiltersComponent.js#L43
