### ISSUE TITLE
cant'load users image 

### ISSUE THREAD

**Issue by stepupithubapp** [GregoryNative/react-native-gl-image-filters#6]
how to load image from device ?
like file:///storage/emulator/0/abc.jpg

**Comment by stepupithubapp** [comment]
#GregoryNative  plz help me

**Comment by stepupithubapp** [comment]
@GregoryNative

**Comment by GregoryNative** [comment]
Hello. This module use **gl-react-native** under the hood. You can ask your question firstly here https://github.com/gre/gl-react-native-v2

@stepupithubapp
